require('dotenv').config()

const {
  PORT = 3000,
  MONGODB_URI_CONNECTION,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXP_TIME,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXP_TIME,
  BCRYPT_SALT_ROUNDS
} = process.env

module.exports = {
  PORT,
  MONGODB_URI_CONNECTION,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXP_TIME,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXP_TIME,
  BCRYPT_SALT_ROUNDS: Number(BCRYPT_SALT_ROUNDS)
}
